const colors = {
  blue: {
    50: 'rgb(var(--blue-50))',
    100: 'rgb(var(--blue-100))',
    200: 'rgb(var(--blue-200))',
    300: 'rgb(var(--blue-300))',
    400: 'rgb(var(--blue-400))',
    500: 'rgb(var(--blue-500))',
    600: 'rgb(var(--blue-600))',
    700: 'rgb(var(--blue-700))',
    800: 'rgb(var(--blue-800))',
    900: 'rgb(var(--blue-900))',
    950: 'rgb(var(--blue-950))',
  },

  lightblue: {
    50: 'rgb(var(--lightblue-50))',
    100: 'rgb(var(--lightblue-100))',
    200: 'rgb(var(--lightblue-200))',
    300: 'rgb(var(--lightblue-300))',
    400: 'rgb(var(--lightblue-400))',
    500: 'rgb(var(--lightblue-500))',
    600: 'rgb(var(--lightblue-600))',
    700: 'rgb(var(--lightblue-700))',
    800: 'rgb(var(--lightblue-800))',
    900: 'rgb(var(--lightblue-900))',
    950: 'rgb(var(--lightblue-950))',
  },

  purple: {
    50: 'rgb(var(--purple-50))',
    100: 'rgb(var(--purple-100))',
    200: 'rgb(var(--purple-200))',
    300: 'rgb(var(--purple-300))',
    400: 'rgb(var(--purple-400))',
    500: 'rgb(var(--purple-500))',
    600: 'rgb(var(--purple-600))',
    700: 'rgb(var(--purple-700))',
    800: 'rgb(var(--purple-800))',
    900: 'rgb(var(--purple-900))',
    950: 'rgb(var(--purple-950))',
  },

  navyvarient: {
    50: 'rgb(var(--navyvarient-50))',
    100: 'rgb(var(--navyvarient-100))',
    200: 'rgb(var(--navyvarient-200))',
    300: 'rgb(var(--navyvarient-300))',
    400: 'rgb(var(--navyvarient-400))',
    500: 'rgb(var(--navyvarient-500))',
    600: 'rgb(var(--navyvarient-600))',
    700: 'rgb(var(--navyvarient-700))',
    800: 'rgb(var(--navyvarient-800))',
    900: 'rgb(var(--navyvarient-900))',
    950: 'rgb(var(--navyvarient-950))',
  },

  navy: {
    50: 'rgb(var(--navy-50))',
    100: 'rgb(var(--navy-100))',
    200: 'rgb(var(--navy-200))',
    300: 'rgb(var(--navy-300))',
    400: 'rgb(var(--navy-400))',
    500: 'rgb(var(--navy-500))',
    600: 'rgb(var(--navy-600))',
    700: 'rgb(var(--navy-700))',
    800: 'rgb(var(--navy-800))',
    900: 'rgb(var(--navy-900))',
    950: 'rgb(var(--navy-950))',
  },

  grayscale: {
    50: 'rgb(var(--grayscale-50))',
    100: 'rgb(var(--grayscale-100))',
    200: 'rgb(var(--grayscale-200))',
    300: 'rgb(var(--grayscale-300))',
    400: 'rgb(var(--grayscale-400))',
    500: 'rgb(var(--grayscale-500))',
    600: 'rgb(var(--grayscale-600))',
    700: 'rgb(var(--grayscale-700))',
    800: 'rgb(var(--grayscale-800))',
    900: 'rgb(var(--grayscale-900))',
    950: 'rgb(var(--grayscale-950))',
  },

  red: {
    50: 'rgb(var(--red-50))',
    100: 'rgb(var(--red-100))',
    200: 'rgb(var(--red-200))',
    300: 'rgb(var(--red-300))',
    400: 'rgb(var(--red-400))',
    500: 'rgb(var(--red-500))',
    600: 'rgb(var(--red-600))',
    700: 'rgb(var(--red-700))',
    800: 'rgb(var(--red-800))',
    900: 'rgb(var(--red-900))',
    950: 'rgb(var(--red-950))',
  },

  green: {
    50: 'rgb(var(--green-50))',
    100: 'rgb(var(--green-100))',
    200: 'rgb(var(--green-200))',
    300: 'rgb(var(--green-300))',
    400: 'rgb(var(--green-400))',
    500: 'rgb(var(--green-500))',
    600: 'rgb(var(--green-600))',
    700: 'rgb(var(--green-700))',
    800: 'rgb(var(--green-800))',
    900: 'rgb(var(--green-900))',
    950: 'rgb(var(--green-950))',
  },

  yellow: {
    50: 'rgb(var(--yellow-50))',
    100: 'rgb(var(--yellow-100))',
    200: 'rgb(var(--yellow-200))',
    300: 'rgb(var(--yellow-300))',
    400: 'rgb(var(--yellow-400))',
    500: 'rgb(var(--yellow-500))',
    600: 'rgb(var(--yellow-600))',
    700: 'rgb(var(--yellow-700))',
    800: 'rgb(var(--yellow-800))',
    900: 'rgb(var(--yellow-900))',
    950: 'rgb(var(--yellow-950))',
  },

  'blue-highest-dark': 'rgb(var(--blue-highest-dark))',
  'blue-highest': 'rgb(var(--blue-highest))',
  'blue-high-dark': 'rgb(var(--blue-high-dark))',
  'blue-high': 'rgb(var(--blue-high))',
  'blue-low-dark': 'rgb(var(--blue-low-dark))',
  'blue-low': 'rgb(var(--blue-low))',
  'blue-lowest-dark': 'rgb(var(--blue-lowest-dark))',
  'blue-lowest': 'rgb(var(--blue-lowest))',

  'lightblue-highest-dark': 'rgb(var(--lightblue-highest-dark))',
  'lightblue-highest': 'rgb(var(--lightblue-highest))',
  'lightblue-high-dark': 'rgb(var(--lightblue-high-dark))',
  'lightblue-high': 'rgb(var(--lightblue-high))',
  'lightblue-low-dark': 'rgb(var(--lightblue-low-dark))',
  'lightblue-low': 'rgb(var(--lightblue-low))',
  'lightblue-lowest-dark': 'rgb(var(--lightblue-lowest-dark))',
  'lightblue-lowest': 'rgb(var(--lightblue-lowest))',

  'purple-highest-dark': 'rgb(var(--purple-highest-dark))',
  'purple-highest': 'rgb(var(--purple-highest))',
  'purple-high-dark': 'rgb(var(--purple-high-dark))',
  'purple-high': 'rgb(var(--purple-high))',
  'purple-low-dark': 'rgb(var(--purple-low-dark))',
  'purple-low': 'rgb(var(--purple-low))',
  'purple-lowest-dark': 'rgb(var(--purple-lowest-dark))',
  'purple-lowest': 'rgb(var(--purple-lowest))',

  'gs-depth-1-dark': 'rgb(var(--gs-depth-1-dark))',
  'gs-depth-1': 'rgb(var(--gs-depth-1))',
  'gs-depth-2-dark': 'rgb(var(--gs-depth-2-dark))',
  'gs-depth-2': 'rgb(var(--gs-depth-2))',
  'gs-depth-3-dark': 'rgb(var(--gs-depth-3-dark))',
  'gs-depth-3': 'rgb(var(--gs-depth-3))',
  'gs-depth-4-dark': 'rgb(var(--gs-depth-4-dark))',
  'gs-depth-4': 'rgb(var(--gs-depth-4))',
  'gs-depth-5-dark': 'rgb(var(--gs-depth-5-dark))',
  'gs-depth-5': 'rgb(var(--gs-depth-5))',
  'gs-depth-6-dark': 'rgb(var(--gs-depth-6-dark))',
  'gs-depth-6': 'rgb(var(--gs-depth-6))',
  'gs-depth-7-dark': 'rgb(var(--gs-depth-7-dark))',
  'gs-depth-7': 'rgb(var(--gs-depth-7))',

  'navy-depth-1-dark': 'rgb(var(--navy-depth-1-dark))',
  'navy-depth-1': 'rgb(var(--navy-depth-1))',
  'navy-depth-2-dark': 'rgb(var(--navy-depth-2-dark))',
  'navy-depth-2': 'rgb(var(--navy-depth-2))',
  'navy-depth-3-dark': 'rgb(var(--navy-depth-3-dark))',
  'navy-depth-3': 'rgb(var(--navy-depth-3))',
  'navy-depth-4-dark': 'rgb(var(--navy-depth-4-dark))',
  'navy-depth-4': 'rgb(var(--navy-depth-4))',
  'navy-depth-5-dark': 'rgb(var(--navy-depth-5-dark))',
  'navy-depth-5': 'rgb(var(--navy-depth-5))',
  'navy-depth-6-dark': 'rgb(var(--navy-depth-6-dark))',
  'navy-depth-6': 'rgb(var(--navy-depth-6))',
  'navy-depth-7-dark': 'rgb(var(--navy-depth-7-dark))',
  'navy-depth-7': 'rgb(var(--navy-depth-7))',
  'navy-depth-8-dark': 'rgb(var(--navy-depth-8-dark))',
  'navy-depth-8': 'rgb(var(--navy-depth-8))',

  'nv-depth-1-dark': 'rgb(var(--nv-depth-1-dark))',
  'nv-depth-1': 'rgb(var(--nv-depth-1))',
  'nv-depth-2-dark': 'rgb(var(--nv-depth-2-dark))',
  'nv-depth-2': 'rgb(var(--nv-depth-2))',
  'nv-depth-3-dark': 'rgb(var(--nv-depth-3-dark))',
  'nv-depth-3': 'rgb(var(--nv-depth-3))',

  'gs-primarydepth-dark': 'rgb(var(--gs-primarydepth-dark))',
  'gs-primarydepth': 'rgb(var(--gs-primarydepth))',
  'gs-secondarydepth-dark': 'rgb(var(--gs-secondarydepth-dark))',
  'gs-secondarydepth': 'rgb(var(--gs-secondarydepth))',
  'gs-tertiarydepth-dark': 'rgb(var(--gs-tertiarydepth-dark))',
  'gs-tertiarydepth': 'rgb(var(--gs-tertiarydepth))',
  'gs-subdepth-1-dark': 'rgb(var(--gs-subdepth-1-dark))',
  'gs-subdepth-1': 'rgb(var(--gs-subdepth-1))',
  'gs-subdepth-2-dark': 'rgb(var(--gs-subdepth-2-dark))',
  'gs-subdepth-2': 'rgb(var(--gs-subdepth-2))',
  'gs-whitefixed-dark': 'rgb(var(--gs-whitefixed-dark))',
  'gs-whitefixed': 'rgb(var(--gs-whitefixed))',
  'gs-blackfixed-dark': 'rgb(var(--gs-blackfixed-dark))',
  'gs-blackfixed': 'rgb(var(--gs-blackfixed))',

  'red-error-1-dark': 'rgb(var(--red-error-1-dark))',
  'red-error-1': 'rgb(var(--red-error-1))',
  'red-error-2-dark': 'rgb(var(--red-error-2-dark))',
  'red-error-2': 'rgb(var(--red-error-2))',

  'green-success-1-dark': 'rgb(var(--green-success-1-dark))',
  'green-success-1': 'rgb(var(--green-success-1))',

  'yellow-caution-1-dark': 'rgb(var(--yellow-caution-1-dark))',
  'yellow-caution-1': 'rgb(var(--yellow-caution-1))',
  'yellow-caution-2-dark': 'rgb(var(--yellow-caution-2-dark))',
  'yellow-caution-2': 'rgb(var(--yellow-caution-2))',
  'yellow-caution-3-dark': 'rgb(var(--yellow-caution-3-dark))',
  'yellow-caution-3': 'rgb(var(--yellow-caution-3))',
}

export default colors
